spring:
  application:
    name: cash-workflow
  liquibase:
    enabled: true
    change-log: classpath:db/db.changelog-master.yaml
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5454/circle-organisation
    password: circle-organisation
    username: circle-organisation

zeebe:
  client:
    broker:
      gateway-address: 127.0.0.1:26500
    security:
      plaintext: true

vanillabp:
  adapters:
    camunda7:
      resources-path: processes

server:
  port: 1111

workerId: test